#!/usr/bin/env python3
"""Scan consolidated extract text for raw-data accession IDs.

Mechanically detects sequence/proteomics repository accessions
(GEO / SRA / ENA / DDBJ / ArrayExpress / PRIDE-ProteomeXchange / MassIVE)
inside the per-paper blocks of ``extract/YYYY-MM-DD_pNN.txt`` files and
prints each hit with surrounding context so a human/LLM can decide whether
the accession is *self-deposited* (generated by this paper) or *cited*
(reused / external data).

This is the reusable, KB-agnostic detection step behind the RawDataAvailable
convention documented in SKILL_RAWDATA.md. It does NOT edit notes and does
NOT classify self-vs-cited — that judgment needs the surrounding prose.

Usage:
    python3 tools/scan_accessions.py                 # scan ./extract, text report
    python3 tools/scan_accessions.py --json          # machine-readable JSON
    python3 tools/scan_accessions.py --extract path  # custom extract dir
    python3 tools/scan_accessions.py --stem Foo2024   # only blocks matching substring
"""
import argparse
import glob
import json
import os
import re
import sys

# repository prefix -> display label (order defines output grouping)
LABELS = [
    ("GSE", "GEO"),
    ("GSM", "GEO"),
    ("PRJNA", "SRA"), ("SRP", "SRA"), ("SRR", "SRA"), ("SRX", "SRA"), ("SRS", "SRA"),
    ("PRJEB", "ENA"), ("ERP", "ENA"), ("ERR", "ENA"), ("ERX", "ENA"),
    ("PRJDB", "DDBJ"), ("DRA", "DDBJ"), ("DRR", "DDBJ"), ("DRX", "DDBJ"),
    ("E-MTAB-", "ArrayExpress"), ("E-GEOD-", "ArrayExpress"), ("E-PROT-", "ArrayExpress"),
    ("PXD", "PRIDE/ProteomeXchange"),
    ("MSV", "MassIVE"),
]
ORDER = ["GEO", "SRA", "ENA", "DDBJ", "ArrayExpress", "PRIDE/ProteomeXchange", "MassIVE"]

ACC_RE = re.compile(
    r"\b("
    r"GSE\d{3,7}|GSM\d{4,9}|"
    r"PRJNA\d{4,}|SRP\d{5,}|SRR\d{5,}|SRX\d{5,}|SRS\d{5,}|"
    r"PRJEB\d{3,}|ERP\d{5,}|ERR\d{5,}|ERX\d{5,}|"
    r"PRJDB\d{3,}|DRA\d{5,}|DRR\d{5,}|DRX\d{5,}|"
    r"E-MTAB-\d{3,}|E-GEOD-\d{3,}|E-PROT-\d{2,}|"
    r"PXD\d{5,}|MSV\d{6,}"
    r")\b"
)
ANCHOR_RE = re.compile(r"^=====\s+(.+?)\s+=====\s*$")


def label_of(acc):
    for prefix, label in LABELS:
        if acc.startswith(prefix):
            return label
    return "Other"


def parse_blocks(extract_dir):
    """Return {note_stem: block_text} across all extract part files."""
    blocks = {}
    for path in sorted(glob.glob(os.path.join(extract_dir, "*.txt"))):
        text = open(path, encoding="utf-8", errors="replace").read()
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        cur, buf = None, []
        for line in text.split("\n"):
            m = ANCHOR_RE.match(line.strip()) if line.startswith("=====") else None
            if m:
                if cur:
                    blocks[cur] = blocks.get(cur, "") + "\n" + "\n".join(buf)
                cur, buf = m.group(1), []
            else:
                buf.append(line)
        if cur:
            blocks[cur] = blocks.get(cur, "") + "\n" + "\n".join(buf)
    return blocks


def scan(extract_dir, stem_filter=None, ctx=160):
    result = {}
    for stem, body in sorted(parse_blocks(extract_dir).items()):
        if stem_filter and stem_filter.lower() not in stem.lower():
            continue
        hits = {}
        for m in ACC_RE.finditer(body):
            acc = m.group(0)
            if acc in hits:
                continue
            s = max(0, m.start() - ctx)
            e = min(len(body), m.end() + 60)
            snippet = re.sub(r"\s+", " ", body[s:e]).strip()
            hits[acc] = {"db": label_of(acc), "context": snippet}
        if hits:
            result[stem] = hits
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--extract", default="extract",
                    help="extract dir holding YYYY-MM-DD_pNN.txt (default: ./extract)")
    ap.add_argument("--stem", default=None, help="only blocks whose stem contains this substring")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of a text report")
    args = ap.parse_args()

    if not os.path.isdir(args.extract):
        sys.exit(f"extract dir not found: {args.extract}")

    result = scan(args.extract, args.stem)

    if args.json:
        json.dump(result, sys.stdout, indent=1, ensure_ascii=False)
        print()
        return

    total = sum(len(v) for v in result.values())
    print(f"# {len(result)} note blocks with >=1 accession, {total} distinct mentions\n")
    for stem, hits in result.items():
        print(f"===== {stem} =====")
        for acc, info in hits.items():
            print(f"[{info['db']}:{acc}] …{info['context']}…")
        print()
    print("# NEXT: for each block decide self-deposited vs cited from the context,")
    print("#       then apply raw_data / RawDataAvailable / Data Availability per SKILL_RAWDATA.md")


if __name__ == "__main__":
    main()
